name: Build and Deploy React app to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
    build-and-deploy:
      
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build
          run: npm install

        - name: Test
          run: npm run test 
          
        - name: Deploy
          run:  |
            git config --global user.name "Chathura-CK"
            git config --global user.email "chathurack@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            npm run deploy
