name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: npm install --legacy-peer-deps

    - name: Test
      run: npm run test 

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run:  |
        git config --global user.name "Chathura-CK"
        git config --global user.email "chathurack@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/${{ github.repository }}
        npm run deploy